### ISSUE TITLE
Front-end launch checklist

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl-react#20]
- [ ] Work over the styles
- [ ] Fancy fonts
- [ ] Create static pages
- [ ] Filters on an organization page:
  - [ ] name
  - [ ] description
  - [ ] type
- [ ] Finish News endpoints
- [ ] Homepage:
  - [ ] Hook up top level stats (#grants, total $) to the stats endpoint
  - [ ] Clean up search result styles
  - [ ] Debounce search
  - [ ] Add a new graphql endpoint for the connected funders 
  - [ ] Most funded NTEE codes
- [ ] CSV exports
- [ ] NTEE code pages (client + server)
  - [ ] Highcharts or similar nice-looking graphs
- [ ] Add trigger to update materialized view totals (server)
- [ ] Re-add chat support (Olark)
  - [ ] Include "report missing or inaccurate data" feature
- [ ] Mailchimp subscription box
- [ ] Pages for individual grants (+ related grants)
- [ ] Redirects for old URLs 
- [ ] Add search bar to the top 
- [ ] Update IRS data!
